### PR TITLE
com.palm.app.calendar: Add high res launcher icons

### PR DESCRIPTION
**Pull request by Herrie82**
Signed-off-by: Herman van Hazendonk github.com@herrie.org

### CODE REVIEW

**Review by Tofee — COMMENTED** [review]
1024x1024 ? Isn't that a bit too much ? I'm a bit worried about memory consumption...

**Comment by Herrie82** [comment]
We load only 1 at a time ;) So I don't think the 200kb will be an issue?

**Comment by Tofee** [comment]
It will be 4Mb in memory

**Comment by Herrie82** [comment]
All our icons are that way for future 4k devices ;)

**Pull request merged**
